

development:
  adapter: mysql2
  database: my_devel
  pool: 5
  host: localhost
  user:  site
  password: 'm23s14m78'


test:
  adapter: mysql2
  database: my_test
  pool: 5
  host: localhost
  user: site
  password: 'm23s14m78'

production:
  adapter: mysql2
  database: my_produc
  pool: 5
  host: localhost
  user: site
  password: 'm23s14m78'

